name: fast-leaf-decay
version: '${project.version}'
main: com.lukeonuke.fastleafdecay.FastLeafDecay
api-version: '26.1.2'
folia-supported: true
description: A fast leaf decay plugin for Spigot and Paper servers.
author: LukeOnuke
contributors: [ElectricSteve]
website: https://github.com/LukeOnuke/fast-leaf-decay/